"""add deleted_at to brands

Revision ID: 90e274faf2ba
Revises: 85d17a8f1205
Create Date: 2026-01-03 19:30:50.587602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e274faf2ba'
down_revision: Union[str, Sequence[str], None] = '85d17a8f1205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'deleted_at')
    # ### end Alembic commands ###
