"""remove_category_from_products

Revision ID: d1899f05048e
Revises: 67f01b473dd2
Create Date: 2026-01-06 16:30:13.462042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd1899f05048e'
down_revision: Union[str, Sequence[str], None] = '67f01b473dd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('products_ibfk_2'), 'products', type_='foreignkey')
    op.drop_column('products', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('products_ibfk_2'), 'products', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
