"""Add soft delete to products

Revision ID: db420a48019a
Revises: 85d17a8f1205
Create Date: 2026-01-05 22:52:29.216263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db420a48019a'
down_revision: Union[str, Sequence[str], None] = '85d17a8f1205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'deleted_at')
    op.drop_column('products', 'is_deleted')
    # ### end Alembic commands ###
